import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "@/app/globals.css";

import ReactQueryProvider from "@/providers/ReactQueryProvider";
import BackendStatusBoundary from "@/components/BackendStatusBoundary";

import { ThemeProvider } from "@/hooks/useTheme";
import Cursor from "@/components/Cursor";
import GlobalContextMenu from "@/components/GlobalContextMenu";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({ variable: "--font-inter", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`cursor-none antialiased ${geistSans.variable} ${geistMono.variable} ${inter.variable}`}
      >
        <ReactQueryProvider>
          <ThemeProvider>
            <BackendStatusBoundary>
              <GlobalContextMenu>{children}</GlobalContextMenu>
              <Cursor />
            </BackendStatusBoundary>
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
