name: Test

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ develop ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install backend dependencies
        working-directory: ./backend
        run: bun install
      
      - name: Setup test environment
        working-directory: ./backend
        run: |
          echo "DATABASE_URL=postgresql://postgres:testpassword@localhost:5432/testdb?schema=public" > .env
          echo "JWT_SECRET=test-secret-key" >> .env
      
      - name: Run Prisma migrations
        working-directory: ./backend
        run: bun run prisma migrate deploy
      
      - name: Run backend tests
        working-directory: ./backend
        run: bun test || echo "No tests configured"

  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json
      
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Run linter
        working-directory: ./frontend
        run: npm run lint || echo "No lint configured"
      
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
      
      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test || echo "No tests configured"